In [1]:
import pandas as pd
import json

### Load `inventory_response_data` json

In [2]:
with open('inventory_response_1.json') as f:
    data = json.load(f)

print("num rows: ", len(data['rows']))

inventory_df = pd.DataFrame(data['rows'])

print("inventory_df shape: ", inventory_df.shape)

inventory_df.head(5)

num rows:  2018
inventory_df shape:  (2018, 66)

,inHandDate,id,accountId,eventId,quantity,notes,section,row,secondRow,lowSeat,...,hold,unitCostAverage,faceValueAverage,currencies,received,vendorId,inHand,hasTaxedCost,daysOld,event
0,2022-05-09,229463055,1797,3752085,8,TEST INVENTORY,TEST,TEST,None,9999,...,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3752085, 'name': 'Rod Stewart', 'date':..."
1,2022-05-09,229465128,1797,3514051,8,TEST INVENTORY,TEST,TEST,None,9999,...,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3514051, 'name': 'Justin Bieber (Resche..."
2,2022-05-09,229465129,1797,3514049,8,TEST INVENTORY,TEST,TEST,None,9999,...,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3514049, 'name': 'Justin Bieber (Postpo..."
3,2022-05-09,229465130,1797,3938200,8,TEST INVENTORY,TEST,TEST,None,9999,...,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3938200, 'name': 'Justin Bieber', 'date..."
4,2022-05-09,229465485,1797,3637558,4,TEST INVENTORY,TEST,TEST,None,9999,...,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3637558, 'name': 'Wicked', 'date': '202..."

In [3]:
list(inventory_df.columns)[:8]

['inHandDate',
 'id',
 'accountId',
 'eventId',
 'quantity',
 'notes',
 'section',
 'row']

In [4]:
dtypes = inventory_df.dtypes
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dtypes[:20])

inHandDate           object
id                    int64
accountId             int64
eventId               int64
quantity              int64
notes                object
section              object
row                  object
secondRow            object
lowSeat               int64
highSeat              int64
cost                float64
taxedCost           float64
taxedCostAverage    float64
faceValue           float64
tickets              object
ticketIds            object
stockType            object
splitType            object
customSplit          object
dtype: object

### unravel objects within a field: e.g. `event`

In [7]:
event_df = inventory_df['event'].apply(pd.Series)
print(event_df.shape)
event_df.head(5)

(2018, 19)

,id,name,date,venue,performerId,performer,keywords,chartUrl,stubhubEventId,stubhubEventUrl,tags,notes,eiEventId,optOutReplenishment,ticketCount,mySoldTickets,myCancelledTickets,disabled,vividSeatsEventUrl
0,3752085,Rod Stewart,2022-10-01T19:30:00,"{'id': 2123, 'name': 'Caesars Palace', 'addres...",733,"{'id': 733, 'name': 'Rod Stewart', 'eventType'...","Rod Stewart, Caesars Palace, Las Vegas, NV, Ro...",http://d2o50i5c2dr30a.cloudfront.net/fc70d9d2-...,105047031,https://www.stubhub.com/rod-stewart-las-vegas-...,None,None,3280938,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...
1,3514051,Justin Bieber (Rescheduled from 7/13/2021) (Po...,2099-06-13T19:30:00,"{'id': 973, 'name': 'Madison Square Garden', '...",22202,"{'id': 22202, 'name': 'Justin Bieber', 'eventT...","Justin Bieber, Madison Square Garden, New York...",http://d2o50i5c2dr30a.cloudfront.net/ad353c42-...,104708929,https://www.stubhub.com/justin-bieber-new-york...,None,None,0,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...
2,3514049,Justin Bieber (Postponed - Date TBD),2099-06-20T19:30:00,"{'id': 573, 'name': 'TD Garden', 'address': '1...",22202,"{'id': 22202, 'name': 'Justin Bieber', 'eventT...","Justin Bieber, TD Garden, Boston, MA, Justin B...",http://d2o50i5c2dr30a.cloudfront.net/b954d13a-...,104708923,https://www.stubhub.com/justin-bieber-boston-t...,None,None,3041492,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...
3,3938200,Justin Bieber,2022-10-25T23:59:00,"{'id': 20419, 'name': 'Singapore National Stad...",22202,"{'id': 22202, 'name': 'Justin Bieber', 'eventT...","Justin Bieber, Singapore National Stadium, Sin...",http://d2o50i5c2dr30a.cloudfront.net/chart-cs.gif,0,None,None,None,0,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...
4,3637558,Wicked,2022-06-05T13:00:00,"{'id': 1223, 'name': 'Ohio Theatre - Columbus'...",4167,"{'id': 4167, 'name': 'Wicked', 'eventType': 'T...","Wicked, Ohio Theatre - Columbus, Columbus, OH,...",http://d2o50i5c2dr30a.cloudfront.net/6c7beca1-...,104875863,https://www.stubhub.com/wicked-columbus-columb...,None,None,0,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...

In [8]:
event_df.dtypes

id                      int64
name                   object
date                   object
venue                  object
performerId             int64
performer              object
keywords               object
chartUrl               object
stubhubEventId          int64
stubhubEventUrl        object
tags                   object
notes                  object
eiEventId               int64
optOutReplenishment      bool
ticketCount            object
mySoldTickets           int64
myCancelledTickets      int64
disabled                 bool
vividSeatsEventUrl     object
dtype: object

In [10]:
event_venue_df = event_df['venue'].apply(pd.Series)

print(event_venue_df.shape)
event_venue_df.head(5)

(2018, 9)

,id,name,address,city,state,country,postalCode,phone,timeZone
0,2123,Caesars Palace,3570 S. Las Vegas Blvd. South,Las Vegas,NV,US,89109,866-227-5938,America/Los_Angeles
1,973,Madison Square Garden,4 Pennsylvania Plaza,New York,NY,US,10001,212-465-6741,America/New_York
2,573,TD Garden,100 Legends Way,Boston,MA,US,02114,617-624-1750,America/New_York
3,20419,Singapore National Stadium,1 Stadium Drive,Singapore,None,CN,397629,65 6653 8900,Asia/Singapore
4,1223,Ohio Theatre - Columbus,39 E. State St.,Columbus,OH,US,43215,614-469-0939,America/New_York

### Build Full Data

In [11]:
event_df.columns = ["event_" + col for col in event_df.columns]
event_venue_df.columns = ["event_venue_" + col for col in event_venue_df.columns]

In [12]:
df = pd.concat([inventory_df, event_df, event_venue_df], axis=1 )

In [13]:
df.shape

(2018, 94)

In [14]:
from IPython.display import display

In [15]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df.head(5))

,inHandDate,id,accountId,eventId,quantity,notes,section,row,secondRow,lowSeat,highSeat,cost,taxedCost,taxedCostAverage,faceValue,tickets,ticketIds,stockType,splitType,customSplit,listPrice,expectedValue,publicNotes,attributes,status,inHandDaysBeforeEvent,lastPriceUpdate,createdDate,createdBy,lastUpdateBy,version,tags,seatType,eventMapping,mappingId,exchangePosId,broadcast,zoneSeating,electronicTransfer,optOutAutoPrice,hideSeatNumbers,vsrOption,replenishmentGroupId,replenishmentGroup,shownQuantity,ticketsMerged,ticketsSplit,filesUploaded,barCodesEntered,instantTransfer,instantTransferOptedOut,seatNumbers,listed,consignmentStatus,cooperative,holdId,hold,unitCostAverage,faceValueAverage,currencies,received,vendorId,inHand,hasTaxedCost,daysOld,event,event_id,event_name,event_date,event_venue,event_performerId,event_performer,event_keywords,event_chartUrl,event_stubhubEventId,event_stubhubEventUrl,event_tags,event_notes,event_eiEventId,event_optOutReplenishment,event_ticketCount,event_mySoldTickets,event_myCancelledTickets,event_disabled,event_vividSeatsEventUrl,event_venue_id,event_venue_name,event_venue_address,event_venue_city,event_venue_state,event_venue_country,event_venue_postalCode,event_venue_phone,event_venue_timeZone
0,2022-05-09,229463055,1797,3752085,8,TEST INVENTORY,TEST,TEST,None,9999,10006,0.0,0.0,0.0,0.0,[],"[927682903, 927682904, 927682905, 927682906, 9...",HARD,DEFAULT,None,NaN,None,None,[],AVAILABLE,None,2022-05-09T17:14:48.000Z,2022-05-09T17:14:48.000Z,None,None,1652116488000,project test,CONSECUTIVE,None,0,274686842,True,False,False,False,False,ALL,0.0,None,None,None,None,False,False,False,False,"9999,10000,10001,10002,10003,10004,10005,10006",False,No,False,None,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3752085, 'name': 'Rod Stewart', 'date':...",3752085,Rod Stewart,2022-10-01T19:30:00,"{'id': 2123, 'name': 'Caesars Palace', 'addres...",733,"{'id': 733, 'name': 'Rod Stewart', 'eventType'...","Rod Stewart, Caesars Palace, Las Vegas, NV, Ro...",http://d2o50i5c2dr30a.cloudfront.net/fc70d9d2-...,105047031,https://www.stubhub.com/rod-stewart-las-vegas-...,None,None,3280938,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...,2123,Caesars Palace,3570 S. Las Vegas Blvd. South,Las Vegas,NV,US,89109,866-227-5938,America/Los_Angeles
1,2022-05-09,229465128,1797,3514051,8,TEST INVENTORY,TEST,TEST,None,9999,10006,0.0,0.0,0.0,0.0,[],"[927691061, 927691062, 927691063, 927691064, 9...",HARD,DEFAULT,None,NaN,None,None,[],AVAILABLE,None,2022-05-09T17:15:59.000Z,2022-05-09T17:15:59.000Z,None,None,1652116560000,project test,CONSECUTIVE,None,0,274688949,True,False,False,False,False,ALL,0.0,None,None,None,None,False,False,False,False,"9999,10000,10001,10002,10003,10004,10005,10006",False,No,False,None,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3514051, 'name': 'Justin Bieber (Resche...",3514051,Justin Bieber (Rescheduled from 7/13/2021) (Po...,2099-06-13T19:30:00,"{'id': 973, 'name': 'Madison Square Garden', '...",22202,"{'id': 22202, 'name': 'Justin Bieber', 'eventT...","Justin Bieber, Madison Square Garden, New York...",http://d2o50i5c2dr30a.cloudfront.net/ad353c42-...,104708929,https://www.stubhub.com/justin-bieber-new-york...,None,None,0,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...,973,Madison Square Garden,4 Pennsylvania Plaza,New York,NY,US,10001,212-465-6741,America/New_York
2,2022-05-09,229465129,1797,3514049,8,TEST INVENTORY,TEST,TEST,None,9999,10006,0.0,0.0,0.0,0.0,[],"[927691069, 927691070, 927691071, 927691072, 9...",HARD,DEFAULT,None,NaN,None,None,[],AVAILABLE,None,2022-05-09T17:15:59.000Z,2022-05-09T17:15:59.000Z,None,None,1652116560000,project test,CONSECUTIVE,None,0,274688950,True,False,False,False,False,ALL,0.0,None,None,None,None,False,False,False,False,"9999,10000,10001,10002,10003,10004,10005,10006",False,No,False,None,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3514049, 'name': 'Justin Bieber (Postpo...",3514049,Justin Bieber (Postponed - Date TBD),2099-06-20T19:30:00,"{'id': 573, 'name': 'TD Garden', 'address': '1...",22202,"{'id': 22202, 'name': 'Justin Bieber', 'eventT...","Justin Bieber, TD Garden, Boston, MA, Justin B...",http://d2o50i5c2dr30a.cloudfront.net/b954d13a-...,104708923,https://www.stubhub.com/justin-bieber-boston-t...,None,None,3041492,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...,573,TD Garden,100 Legends Way,Boston,MA,US,02114,617-624-1750,America/New_York
3,2022-05-09,229465130,1797,3938200,8,TEST INVENTORY,TEST,TEST,None,9999,10006,0.0,0.0,0.0,0.0,[],"[927691077, 927691078, 927691079, 927691080, 9...",HARD,DEFAULT,None,NaN,None,None,[],AVAILABLE,None,2022-05-09T17:15:59.000Z,2022-05-09T17:15:59.000Z,None,None,1652116560000,project test,CONSECUTIVE,None,0,274688951,True,False,False,False,False,ALL,0.0,None,None,None,None,False,False,False,False,"9999,10000,10001,10002,10003,10004,10005,10006",False,No,False,None,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3938200, 'name': 'Justin Bieber', 'date...",3938200,Justin Bieber,2022-10-25T23:59:00,"{'id': 20419, 'name': 'Singapore National Stad...",22202,"{'id': 22202, 'name': 'Justin Bieber', 'eventT...","Justin Bieber, Singapore National Stadium, Sin...",http://d2o50i5c2dr30a.cloudfront.net/chart-cs.gif,0,None,None,None,0,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...,20419,Singapore National Stadium,1 Stadium Drive,Singapore,None,CN,397629,65 6653 8900,Asia/Singapore
4,2022-05-09,229465485,1797,3637558,4,TEST INVENTORY,TEST,TEST,None,9999,10002,0.0,0.0,0.0,0.0,[],"[927692943, 927692944, 927692945, 927692946]",HARD,DEFAULT,None,NaN,None,None,[],AVAILABLE,None,2022-05-09T17:17:25.000Z,2022-05-09T17:17:25.000Z,None,None,1652116646000,project test,CONSECUTIVE,None,0,274689332,True,False,False,False,False,ALL,0.0,None,None,None,None,False,False,False,False,"9999,10000,10001,10002",False,No,False,None,None,0.0,0.0,[USD],No,[631321],True,None,72,"{'id': 3637558, 'name': 'Wicked', 'date': '202...",3637558,Wicked,2022-06-05T13:00:00,"{'id': 1223, 'name': 'Ohio Theatre - Columbus'...",4167,"{'id': 4167, 'name': 'Wicked', 'eventType': 'T...","Wicked, Ohio Theatre - Columbus, Columbus, OH,...",http://d2o50i5c2dr30a.cloudfront.net/6c7beca1-...,104875863,https://www.stubhub.com/wicked-columbus-columb...,None,None,0,False,None,0,0,False,http://www.vividseats.com/shop/viewTickets.sht...,1223,Ohio Theatre - Columbus,39 E. State St.,Columbus,OH,US,43215,614-469-0939,America/New_York